### ISSUE TITLE
Contributions and Licence?

### ISSUE THREAD

**Issue by pwood** [dyrkin/zigbee-steward#1]
Hello Dyrkin!

After doing some initial looking into zigbee2mqtt, I found your suite of Go libraries for powering the CC2531 USB dongle and it works much better than the z2m in a lot of scenarios (especially pairing devices).

I've done some work on zcl-go (adding more clusters) and I've started on some changes to zigbee-steward (non singleton database, more functions for clusters, etc).

It'd be great to get these back to you so others might be able to benefit from them, and I can stop maintaining nasty replace directives in my go.mod files ;).

If I raised a PR would you consider merging them in? And while I'm not hugely fussed about which open source license, it'd be good to have one attached to the projects to make it clear about the state of contributions, etc. For unp-go, znp-go, zcl-go and zigbee-steward.

I also appreciate that you've not commited to these for 8 months or so, I guess you may not be using them? Would you appreciate a helping hand in maintaining them?

FWIW, my interest is in improving my own home Zigbee ecosystem, dumping the Phillips Hue bridge and interfacing a lot of the lower cost sensors from the Chinese vendors along side the nicer Hue/Tradfri bulbs.

Cheers,

Peter.

**Comment by joonas-fi** [comment]
+1

Architecturally your projects seem cleaner than zigbee2mqtt (+ it's not JavaScript), and I would very much like to stop interfacing with MQTT and embed Zigbee directly into my home automation: https://github.com/function61/hautomo

I would also like to help, if help is needed.

**Comment by dyrkin** [comment]
Hi guys! 
I've added the license file. Currently, I don't have time to contribute to the project, but I can help if needed. 
Feel free to use it on your own.

**Comment by bitver** [comment]
Could you do the same for unp-go, znp-go and zcl-go?

**Comment by dyrkin** [comment]
Done

**Comment by pwood** [comment]
This is great to hear! Unfortunately for me I've gone another direction myself and started a similar project.

However if anyone wants to merge in the work I've done on @dyrkin's ZCL library or refactoring the datastore in the steward, please take this as my confirmation I'm happy for them to be transferred into the existing project under the MIT license.

https://github.com/pwood/zcl-go
https://github.com/pwood/zigbee-steward
